require('config.notify')
require("config.indent-blankline")
require("config.dashboard")
require('config.nvim-treesitter')
require('config.nvim-tree')
require('config.bufferline')
require('config.lualine')
require('config.telescope')
require("config.project")
require('config.comment')
require('config.nvim-autopairs')
require('config.nvim-surround')
require('config.aerial')
require('config.gitsigns')
require('config.floaterm')
require('config.nvim-surround')
-- require('config.markdown-preview')
require('config.todo-comments')
require('config.persistence')
require('config.hop')
require('config.nvim-colorizer')
-- require('config.neovim-session-manager')
