#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  2             \
    bottom_padding               25             \
    left_padding                 2             \
    right_padding                2             \
    window_gap                   02             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    # external_bar                 all:28:0


# yabai -m config top_padding                  25
# yabai -m config bottom_padding               25
# yabai -m config left_padding                 25
# yabai -m config right_padding                25
# yabai -m config window_gap                   20
# yabai -m config external_bar                 all:28:0



yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^访达$" sticky=on layer=above manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^AppCleaner$" sticky=off layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^微信$" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^QQ$" manage=off
yabai -m rule --add app="^腾讯会议$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^音乐$" manage=off
yabai -m rule --add app="^网易云音乐$" manage=off
yabai -m rule --add app="^日历$" manage=off




# show digital colour meter topmost and on all spaces
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on

echo "yabai configuration loaded.."
